eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: zuul
  main:
    allow-bean-definition-overriding: true
zuul:
  routes:
    api-a:
      path: /api-data/**
      serviceId: DATA-SERVICE
    api-b:
      path: /api-view/**
      serviceId: VIEW-SERVICE-FEIGN
server:
  port: 8040