server:
  port: 9011

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
    fetch-registry: true
    register-with-eureka: true

spring:
  application:
    name: view-service-feign
  zipkin:
    base-url: http://localhost:9411
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html

feign:
  hystrix:
    enabled: true
