server:
  port: 8014

spring:
  application:
    name: view-service-feign
  zipkin:
    base-url: http://localhost:9411
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

feign:
  hystrix:
    enabled: true

# 路径访问允许/actuator/bus-refresh
management:
  endpoint:
  endpoints:
    web:
      exposure:
        include: bus-refresh
      cors:
        allowed-origins: "*"
        allowed-methods: "*"