server:
  port: 8030

spring:
  application:
    name: config-server
#    config配置
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/upuphold/config
          search-paths: respo

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/